language: node_js
node_js:
  - '6'

os:
  - linux

branches:
  only:
    - master

script: ./scripts/travis.sh

test: 
cache:
  directories:
    - glacier/node_modules
    - gluon/node_modules

notifications:
  email:
    on_success: never
    on_failure: change
