node_js: latest

os:
  - linux

branches:
  only:
    - master

env:
  - NODE_VERSION="6.3.0"

script: ./scripts/travis.sh

test: 
cache:
  directories:
    - glacier/node_modules
    - gluon/node_modules

notifications:
  email:
    on_success: never
    on_failure: change
