language: node_js
node_js:
- '6'
os:
- linux
branches:
  only:
  - master
before_install:
- chmod +x ./scripts/travis.sh
- chmod +x ./scripts/post-build.sh
script: "./scripts/travis.sh"
test: 
cache:
  directories:
  - node_modules
  - src/node_modules
notifications:
  email:
    on_success: never
    on_failure: change
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: TqpApE5OPITbDr3ReX2dSySc5MYlH5gnUD/83bghbB52mWO5lkJpmryIci2Mlqh4nTcoaOPMq5nAVx1e2/IH8f5Xsbm/C0xOTcnuPX5n1t8NYuVzgm1aqcgiPd0bfqvXoDCYkDAQHWZAojJ6deNTSJ+x6kmW8WSL+mEAyL3wB5VkzEdoP4Te2gorzrN9OLsen1S8d4tf8ls9S031zs9oncH5KYD6xalugD6vOYl+4CydV4SvkkyaoOX2OW1gQ+bhou0sQfBYrQeNx/KKt4pUCKveKLfuNxLJk1Mef0QOfdAMi53pwu+Dh9mp5wriyeFZPqJpydACYPBwUWjOktu8LK3pzsjV2CtyPAW8j+gEy9Evxf3SRJrQehmWP1dxsJ6a7zWrXwFS3QtVVwT8Nglbb821yii/002ykkiGJP/bRKAY1iLfd2ckJ/c2LP+n4RKhjGetSpLi8s1E5q2XwL7C6g3ODxqpIt2AXxLgDxJ5bMZYUEdDsPuApoPF769cWAG5+htI8AE7mu6qS9hDAa86Lmyjcjc+QP62n30XToUT8Z9gMcmsPTAFszjX57YBCouVEGHxGAlaAu4zVfqM398/O0E6pcBnIMDKPmg6GFysEFwW1SNw9dohOtVZ/wmJPeVGI2kewBi6NV13sgYKw5YtiCWAq0+5aYSDSkyTrAQlclg=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libcairo2-dev
    - libjpeg-dev
    - libpango1.0-dev
    - libgif-dev
    - build-essential
    - g++-4.8
after_success:
- "./scripts/post-build.sh"
